import type { Metadata } from 'next';
import StyledComponentsRegistry from './lib/registry';
import { poppins } from './ui/fonts/fonts';
import { GlobalStyled } from './ui/styles/Globals';

export const metadata: Metadata = {
	title: 'Rick Bloty',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<StyledComponentsRegistry>
					{children}
					<GlobalStyled />
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
