import type { Metadata } from 'next';
import Footer from './ui/_components/Footer';
import Header from './ui/_components/Header';
import MainContainer from './ui/_components/Main';
import StyledComponentsRegistry from './ui/_components/registry';
import { poppins } from './ui/fonts/fonts';

export const metadata: Metadata = {
	title: 'Rick Bloty',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<StyledComponentsRegistry>
					<Header />
					<MainContainer>{children}</MainContainer>
					<Footer />
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
